### ISSUE TITLE
Replacing forwardslashes

### ISSUE THREAD

**Issue by SgtPooki** [VFK/gulp-html-replace#29]
plugin unexpectedly replaces forward slashes:

```html
        <!-- build:js -->
        <script src="/assets/scripts/lib/require/require.js" data-main="/assets/scripts/main"></script>
        <!-- endbuild -->
```

```js
            gulp.src('index.html')
                .pipe(htmlreplace({
                    js: {
                        src: '/assets/scripts/main.js',
                        tpl: '<script="%s">'
                    }
                }))
                .pipe(chmod(777))
                .pipe(gulp.dest(paths.html.dest));
```

results in 
```
<script="  assets scripts main.js">
```

**Comment by VFK** [comment]
Hm... Are you sure that `chmod(777)` thing don't do anything bad with the output? Because i tried your code without chmod and i got this:
```html
        <script="/assets/scripts/main.js">
```
which looks ok to me. What's your OS? Are you using the latest versions of everything (this plugin, gulp itself, etc.)?

**Comment by VFK** [comment]
So, i tried your exact code (with chmod) on OS X and Win 8.1 and everything was fine.Clearly something else breaks the output. I'm closing this issue because you don't want to talk :) but if you still has the issues on the latest version of this plugin then please open the new issue and provide the full gulp file and your html if possible.

**Comment by SgtPooki** [comment]
Haha, sorry about "not wanting to talk."

I did resolve this issue but I don't remember what the exact cause was. It wasn't chmod..  Thanks for the responses though!
